// <auto-generated />
using System;
using CDatos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CDatos.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250901231627_add11")]
    partial class add11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shared.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoId = 1,
                            Nombre = "Bebidas"
                        },
                        new
                        {
                            Id = 2,
                            EstadoId = 1,
                            Nombre = "Alimentos"
                        },
                        new
                        {
                            Id = 3,
                            EstadoId = 1,
                            Nombre = "Congelados"
                        });
                });

            modelBuilder.Entity("Shared.Entities.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acp = "A1000",
                            Cp = "1000",
                            EstadoId = 1,
                            Nombre = "Ciudad A"
                        },
                        new
                        {
                            Id = 2,
                            Acp = "B2000",
                            Cp = "2000",
                            EstadoId = 1,
                            Nombre = "Ciudad B"
                        });
                });

            modelBuilder.Entity("Shared.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoId = 1,
                            PersonaId = 7
                        },
                        new
                        {
                            Id = 2,
                            EstadoId = 1,
                            PersonaId = 8
                        },
                        new
                        {
                            Id = 3,
                            EstadoId = 1,
                            PersonaId = 9
                        },
                        new
                        {
                            Id = 4,
                            EstadoId = 2,
                            PersonaId = 10
                        },
                        new
                        {
                            Id = 5,
                            EstadoId = 1,
                            PersonaId = 11
                        },
                        new
                        {
                            Id = 6,
                            EstadoId = 2,
                            PersonaId = 12
                        });
                });

            modelBuilder.Entity("Shared.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoId = 1,
                            Foto = "",
                            PersonaId = 1,
                            SectorId = 1
                        },
                        new
                        {
                            Id = 2,
                            EstadoId = 1,
                            Foto = "",
                            PersonaId = 2,
                            SectorId = 2
                        },
                        new
                        {
                            Id = 3,
                            EstadoId = 1,
                            Foto = "",
                            PersonaId = 3,
                            SectorId = 1
                        },
                        new
                        {
                            Id = 4,
                            EstadoId = 2,
                            Foto = "",
                            PersonaId = 4,
                            SectorId = 2
                        },
                        new
                        {
                            Id = 5,
                            EstadoId = 1,
                            Foto = "",
                            PersonaId = 5,
                            SectorId = 1
                        },
                        new
                        {
                            Id = 6,
                            EstadoId = 2,
                            Foto = "",
                            PersonaId = 6,
                            SectorId = 2
                        });
                });

            modelBuilder.Entity("Shared.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Activo"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Inactivo"
                        });
                });

            modelBuilder.Entity("Shared.Entities.OrdenDeCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistribuidorId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaOrden")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrdenesDeCompra");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistribuidorId = 1,
                            EmpleadoId = 1,
                            FechaOrden = new DateTime(2025, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DistribuidorId = 2,
                            EmpleadoId = 2,
                            FechaOrden = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Shared.Entities.OrdenDeCompraProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadProducto")
                        .HasColumnType("int");

                    b.Property<int>("OrdenDeCompraId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrdenesDeCompraProducto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadProducto = 2,
                            OrdenDeCompraId = 1,
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 2,
                            CantidadProducto = 1,
                            OrdenDeCompraId = 1,
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 3,
                            CantidadProducto = 10,
                            OrdenDeCompraId = 2,
                            ProductoId = 3
                        });
                });

            modelBuilder.Entity("Shared.Entities.OrdenDeVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("DistribuidorId")
                        .HasColumnType("int");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("OrdenesDeVenta");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 1,
                            DistribuidorId = 1,
                            EmpleadoId = 1,
                            EstadoId = 1,
                            FacturaId = 1,
                            Fecha = new DateTime(2025, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 2,
                            DistribuidorId = 2,
                            EmpleadoId = 2,
                            EstadoId = 2,
                            FacturaId = 2,
                            Fecha = new DateTime(2025, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Shared.Entities.OrdenDeVentaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadProducto")
                        .HasColumnType("int");

                    b.Property<int>("OrdenVentaId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrdenesDeVentaProducto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CantidadProducto = 1,
                            OrdenVentaId = 1,
                            ProductoId = 1
                        },
                        new
                        {
                            Id = 2,
                            CantidadProducto = 2,
                            OrdenVentaId = 1,
                            ProductoId = 2
                        },
                        new
                        {
                            Id = 3,
                            CantidadProducto = 5,
                            OrdenVentaId = 2,
                            ProductoId = 3
                        });
                });

            modelBuilder.Entity("Shared.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nro_Doc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo_DocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pérez",
                            CiudadId = 1,
                            Direccion = "Calle Falsa 123",
                            Email = "juan@mail.com",
                            EstadoId = 1,
                            Nombre = "Juan",
                            Nro_Doc = "12345678",
                            Telefono = "11111111",
                            Tipo_DocId = 1
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "García",
                            CiudadId = 1,
                            Direccion = "Av. Siempre Viva 742",
                            Email = "ana@mail.com",
                            EstadoId = 1,
                            Nombre = "Ana",
                            Nro_Doc = "87654321",
                            Telefono = "22222222",
                            Tipo_DocId = 2
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Martínez",
                            CiudadId = 2,
                            Direccion = "Calle Luna 45",
                            Email = "luis@mail.com",
                            EstadoId = 1,
                            Nombre = "Luis",
                            Nro_Doc = "11223344",
                            Telefono = "33333333",
                            Tipo_DocId = 3
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Rodríguez",
                            CiudadId = 2,
                            Direccion = "Av. Sol 99",
                            Email = "maria@mail.com",
                            EstadoId = 2,
                            Nombre = "María",
                            Nro_Doc = "44332211",
                            Telefono = "44444444",
                            Tipo_DocId = 1
                        },
                        new
                        {
                            Id = 5,
                            Apellido = "Sánchez",
                            CiudadId = 1,
                            Direccion = "Calle Norte 10",
                            Email = "pedro@mail.com",
                            EstadoId = 1,
                            Nombre = "Pedro",
                            Nro_Doc = "55555555",
                            Telefono = "55555555",
                            Tipo_DocId = 2
                        },
                        new
                        {
                            Id = 6,
                            Apellido = "Fernández",
                            CiudadId = 2,
                            Direccion = "Av. Sur 20",
                            Email = "lucia@mail.com",
                            EstadoId = 2,
                            Nombre = "Lucía",
                            Nro_Doc = "66666666",
                            Telefono = "66666666",
                            Tipo_DocId = 3
                        },
                        new
                        {
                            Id = 7,
                            Apellido = "Ramírez",
                            CiudadId = 1,
                            Direccion = "Calle Este 30",
                            Email = "carlos@mail.com",
                            EstadoId = 1,
                            Nombre = "Carlos",
                            Nro_Doc = "77777777",
                            Telefono = "77777777",
                            Tipo_DocId = 1
                        },
                        new
                        {
                            Id = 8,
                            Apellido = "López",
                            CiudadId = 2,
                            Direccion = "Av. Oeste 40",
                            Email = "sofia@mail.com",
                            EstadoId = 1,
                            Nombre = "Sofía",
                            Nro_Doc = "88888888",
                            Telefono = "88888888",
                            Tipo_DocId = 2
                        },
                        new
                        {
                            Id = 9,
                            Apellido = "Torres",
                            CiudadId = 1,
                            Direccion = "Calle Sur 50",
                            Email = "miguel@mail.com",
                            EstadoId = 1,
                            Nombre = "Miguel",
                            Nro_Doc = "99999999",
                            Telefono = "99999999",
                            Tipo_DocId = 3
                        },
                        new
                        {
                            Id = 10,
                            Apellido = "Gómez",
                            CiudadId = 2,
                            Direccion = "Av. Norte 60",
                            Email = "valentina@mail.com",
                            EstadoId = 2,
                            Nombre = "Valentina",
                            Nro_Doc = "10101010",
                            Telefono = "10101010",
                            Tipo_DocId = 1
                        },
                        new
                        {
                            Id = 11,
                            Apellido = "Castro",
                            CiudadId = 1,
                            Direccion = "Calle Central 70",
                            Email = "diego@mail.com",
                            EstadoId = 1,
                            Nombre = "Diego",
                            Nro_Doc = "11111112",
                            Telefono = "11111112",
                            Tipo_DocId = 2
                        },
                        new
                        {
                            Id = 12,
                            Apellido = "Vega",
                            CiudadId = 2,
                            Direccion = "Av. Principal 80",
                            Email = "martina@mail.com",
                            EstadoId = 2,
                            Nombre = "Martina",
                            Nro_Doc = "12121212",
                            Telefono = "12121212",
                            Tipo_DocId = 3
                        });
                });

            modelBuilder.Entity("Shared.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PrecioProducto")
                        .HasColumnType("real");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Nombre = "Televisor",
                            PrecioProducto = 10000f,
                            ProveedorId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Nombre = "Celular",
                            PrecioProducto = 5000f,
                            ProveedorId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Nombre = "Pan",
                            PrecioProducto = 100f,
                            ProveedorId = 2
                        });
                });

            modelBuilder.Entity("Shared.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Direccion 1",
                            Email = "email1@dominio.com.ar",
                            EstadoId = 1,
                            Nombre = "Proveedor Uno",
                            Telefono = "Telefono 1"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Direccion 2",
                            Email = "email2@dominio.com.ar",
                            EstadoId = 1,
                            Nombre = "Proveedor Dos",
                            Telefono = "Telefono 2"
                        });
                });

            modelBuilder.Entity("Shared.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sectores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstadoId = 1,
                            Nombre = "Ventas"
                        },
                        new
                        {
                            Id = 2,
                            EstadoId = 1,
                            Nombre = "Administración"
                        });
                });

            modelBuilder.Entity("Shared.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreTipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposDocumento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreTipoDocumento = "DNI"
                        },
                        new
                        {
                            Id = 2,
                            NombreTipoDocumento = "Pasaporte"
                        },
                        new
                        {
                            Id = 3,
                            NombreTipoDocumento = "Libreta De Enrolamiento"
                        });
                });

            modelBuilder.Entity("Shared.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contrasenia = "admin123",
                            EstadoId = 1,
                            NombreUsuario = "admin",
                            PersonaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Contrasenia = "cliente123",
                            EstadoId = 1,
                            NombreUsuario = "cliente1",
                            PersonaId = 7
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
